[package]
name = "token-data-provider-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["abigen"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"